# Defines analysis rules for Flutter projects

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Recommended rules
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_single_quotes
    - sort_pub_dependencies
    - use_key_in_widget_constructors


